// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VentaAutos.Shared.Modelos
{
    public partial class cliente
    {
        [Key]
        public int id_cliente { get; set; }
        [Required]
        [StringLength(100)]
        public string nombre_completo { get; set; }
        [Required]
        [StringLength(15)]
        public string dui { get; set; }
        [Column(TypeName = "date")]
        public DateTime fecha_nacimiento { get; set; }
        [Required]
        [StringLength(14)]
        public string telefono { get; set; }
        [Required]
        [StringLength(150)]
        public string email { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_registro { get; set; }
    }
}