// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VentaAutos.Shared.Modelos
{
    public partial class modelo
    {
        [Key]
        public int id_modelo { get; set; }
        [Required]
        [StringLength(35)]
        public string nombre_modelo { get; set; }
    }
}