// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VentaAutos.Shared.Modelos
{
    public partial class precio
    {
        [Key]
        public int id_precio { get; set; }
        public int? id_vehiculo { get; set; }
        public double precio_x_hora { get; set; }
        public double precio_vehiculo { get; set; }
    }
}