// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VentaAutos.Shared.Modelos
{
    public partial class servicio
    {
        [Key]
        public int id_servicio { get; set; }
        public int? id_cliente { get; set; }
        public int? id_vehiculo { get; set; }
        public double precio_total { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_inicio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_fin { get; set; }
        [Column(TypeName = "text")]
        public string nota { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_creacion { get; set; }
    }
}