// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VentaAutos.Shared.Modelos
{
    public partial class tipo_negocio
    {
        [Key]
        public int id_tipo_negocio { get; set; }
        [Required]
        [StringLength(75)]
        public string nombre_negocio { get; set; }
    }
}