// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VentaAutos.Shared.Modelos
{
    public partial class vehiculo
    {
        [Key]
        public int id_vehiculo { get; set; }
        [StringLength(20)]
        public string nombre_vehiculo { get; set; }
        public int? id_marca { get; set; }
        public int? id_modelo { get; set; }
        public int anio { get; set; }
        public int? id_tipo_negocio { get; set; }
        [Required]
        [StringLength(20)]
        public string estado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_registro { get; set; }
    }
}